version: "3.9"
services:
  bcord:
    build:
      context: .
      # If your Dockerfile is at repo ROOT, use "./Dockerfile" instead:
      dockerfile: ./server/Dockerfile
    container_name: bcord
    environment:
      - BIND_ADDR=0.0.0.0
      - PORT=9000
      - REDIS_URL=redis://redis:6379
      - PGHOST=postgres
      - PGDATABASE=bcord
      - PGUSER=bcord
      - PGPASSWORD=change_me
      - PGPORT=5432
    expose:
      - "9000"
    depends_on: [redis, postgres]

  redis:
    image: redis:7
    container_name: bcord-redis

  postgres:
    image: postgres:16
    container_name: bcord-postgres
    environment:
      - POSTGRES_DB=bcord
      - POSTGRES_USER=bcord
      - POSTGRES_PASSWORD=change_me
    volumes:
      - bcord-pg:/var/lib/postgresql/data

  caddy:
    image: caddy:2
    container_name: bcord-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - ./tester:/srv/tester:ro
    depends_on: [bcord]

volumes:
  bcord-pg:
  caddy-data:
  caddy-config:
